# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://maggie-lou.github.io
title: MAGGIE LOU
email: mlou2019@gmail.com
author: Maggie Lou
description: > # "Hi, I'm Maggie. I'm a sophomore at Northwestern studying Computer Science in the McCormick School of Engineering. I want to use clever and creative programming to produce utility with tangible results. Let's create together.
copyright: 'Copyright &copy; 2016 Maggie Lou. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/maggie-lou
  - title: linkedin
    url: https://www.linkedin.com/in/maggie-lou-4a3bb110a
